### ISSUE TITLE
Is the main screen meant to say Today Widget Setup?

### ISSUE THREAD

**Issue by andyferriby** [GigaF/Quick-Record-Caffeine#1]
Hi, built your app, but all i get when testing on simulator is a white screen with Today Widget Setup on it!

This be a good app if it was finished thats for sure unless im missing something here

**Comment by GigaF** [comment]
Yes because this app is designed to record caffeine intake via Spotlight, so if you can understand Chinese, please try entering "美式咖啡", "拿铁" (because I got the Caffeine data from Taiwan) to the Spotlight to experience the main feature of my app.
And I'd build the main screen because if I didn't, I will not be able to distribute it via TestFlight, iTunes Connect thinks my app is useless, So, you are not miss anything here, the main screen is just simple with Today Widget Setup.
